export const GROUPS = [
  {
    id: 'none',
    eyebrow: '01 · 不縮放',
    title: 'none：保持原始字級',
    description: 'Browser 不調整文字大小，可用來對照原始溢出或剩餘空間。',
  },
  {
    id: 'grow',
    eyebrow: '02 · 放大',
    title: 'grow：放大文字填滿行寬',
    description: '從較小的 base font size 開始，觀察不同行策略如何使用每行剩餘空間。',
  },
  {
    id: 'shrink',
    eyebrow: '03 · 縮小',
    title: 'shrink：縮小文字避免溢出',
    description: '從較大的 base font size 開始，觀察長文字如何縮進容器以及最低比例限制。',
  },
]

export const TEXT_FIT_CASES = [
  {
    id: 'none',
    group: 'none',
    declaration: 'none',
    title: '不進行任何縮放',
    explanation: 'none 是初始值。Browser 保留 42px base font size，不放大也不縮小；後接行策略或百分比也不會產生效果。',
    observation: '拖窄容器時，長標題仍維持原始尺寸並可能溢出。',
    fixture: 'none-overflow',
    baseFontSize: 42,
  },
  {
    id: 'grow-default',
    group: 'grow',
    declaration: 'grow',
    title: '省略行策略',
    explanation: 'grow 只允許放大；省略第二組關鍵字時，Browser 預設採用 consistent，且沒有最大放大限制。',
    observation: '結果應與下一張 grow consistent 相同，所有行共用一個縮放倍率。',
    fixture: 'grow-natural',
    baseFontSize: 18,
  },
  {
    id: 'grow-consistent',
    group: 'grow',
    declaration: 'grow consistent',
    title: '所有行使用相同倍率',
    explanation: 'consistent 取整個容器可共同使用的縮放倍率，讓所有行保持一致的文字尺寸。',
    observation: '各行字級一致；較短的行不一定能完全填滿寬度。',
    fixture: 'grow-natural',
    baseFontSize: 18,
  },
  {
    id: 'grow-per-line',
    group: 'grow',
    declaration: 'grow per-line',
    title: '逐行放大，但排除末行',
    explanation: 'per-line 讓每個自然換行各自計算倍率，但最後一行及以強制換行結束的行不縮放。',
    observation: '前面的自然換行會各自填滿，最後一行維持 18px。',
    fixture: 'grow-natural',
    baseFontSize: 18,
  },
  {
    id: 'grow-per-line-all',
    group: 'grow',
    declaration: 'grow per-line-all',
    title: '包含末行的逐行放大',
    explanation: 'per-line-all 讓每一行獨立計算，也包含最後一行與強制換行結束的行。',
    observation: '最後一行也會被放大；短行的字可能明顯大於長行。',
    fixture: 'grow-natural',
    baseFontSize: 18,
  },
  {
    id: 'grow-consistent-limit',
    group: 'grow',
    declaration: 'grow consistent 200%',
    title: '相同倍率，最多放大兩倍',
    explanation: '200% 是 grow 的最大縮放倍率；18px 的 used font size 最多相當於 36px。',
    observation: '所有行維持相同倍率；空間太寬時仍可能留下空白。',
    fixture: 'grow-limit',
    baseFontSize: 18,
  },
  {
    id: 'grow-per-line-limit',
    group: 'grow',
    declaration: 'grow per-line 200%',
    title: '逐行放大，排除末行並限制兩倍',
    explanation: '每個可處理的行各自放大，但最高 200%；最後一行與強制換行行仍不處理。',
    observation: '前幾行最多放大到兩倍，末行保持 base font size。',
    fixture: 'grow-natural',
    baseFontSize: 18,
  },
  {
    id: 'grow-per-line-all-limit',
    group: 'grow',
    declaration: 'grow per-line-all 200%',
    title: '所有行逐行放大，最多兩倍',
    explanation: '每一行都獨立放大並套用 200% 上限，包含最後一行與強制換行行。',
    observation: '短行也只會放大到兩倍，不會無限制撐滿容器。',
    fixture: 'grow-limit',
    baseFontSize: 18,
  },
  {
    id: 'shrink-default',
    group: 'shrink',
    declaration: 'shrink',
    title: '省略行策略',
    explanation: 'shrink 只允許縮小；省略第二組關鍵字時預設採用 consistent，且沒有最小縮放限制。',
    observation: '結果應與下一張 shrink consistent 相同，全部行以同一倍率縮小。',
    fixture: 'shrink-forced',
    baseFontSize: 46,
  },
  {
    id: 'shrink-consistent',
    group: 'shrink',
    declaration: 'shrink consistent',
    title: '所有行使用相同倍率',
    explanation: 'consistent 依最需要縮小的行決定共同倍率，讓全部行保持相同文字尺寸。',
    observation: '最長的一行剛好放入後，其他行會以相同倍率顯示。',
    fixture: 'shrink-forced',
    baseFontSize: 46,
  },
  {
    id: 'shrink-per-line',
    group: 'shrink',
    declaration: 'shrink per-line',
    title: '逐行縮小，但排除強制換行與末行',
    explanation: 'per-line 各行獨立計算，但不處理最後一行，也不處理以 br 強制結束的行。',
    observation: '此案例刻意使用強制換行；長行會保留 46px 並溢出，凸顯排除規則。',
    fixture: 'shrink-forced',
    baseFontSize: 46,
  },
  {
    id: 'shrink-per-line-all',
    group: 'shrink',
    declaration: 'shrink per-line-all',
    title: '包含所有行的逐行縮小',
    explanation: 'per-line-all 讓每行依自身長度縮小，包含最後一行及以 br 強制結束的行。',
    observation: '三行都會放入容器，而且每一行可能呈現不同的文字尺寸。',
    fixture: 'shrink-forced',
    baseFontSize: 46,
  },
  {
    id: 'shrink-consistent-limit',
    group: 'shrink',
    declaration: 'shrink consistent 50%',
    title: '相同倍率，最低保留一半',
    explanation: '50% 是 shrink 的最小縮放倍率；46px 的 used font size 不會小於相當於 23px。',
    observation: '所有行使用同一倍率；若一半大小仍放不下，內容會繼續溢出。',
    fixture: 'shrink-limit',
    baseFontSize: 46,
  },
  {
    id: 'shrink-per-line-limit',
    group: 'shrink',
    declaration: 'shrink per-line 50%',
    title: '逐行縮小，排除末行並保留一半',
    explanation: '可處理的行各自縮小且最低 50%；最後一行與強制換行行仍排除在縮放之外。',
    observation: '強制換行與末行保持 46px；其餘行即使需要也不會縮到 23px 以下。',
    fixture: 'shrink-forced',
    baseFontSize: 46,
  },
  {
    id: 'shrink-per-line-all-limit',
    group: 'shrink',
    declaration: 'shrink per-line-all 50%',
    title: '所有行逐行縮小，最低保留一半',
    explanation: '所有行獨立縮小並套用 50% 下限，包含最後一行與強制換行行。',
    observation: '每行最多縮到一半；極長文字仍可能溢出，清楚呈現限制效果。',
    fixture: 'shrink-limit',
    baseFontSize: 46,
  },
]

